// ═══════════════════════════════════════════════════════════════════
// MERIDIAN — Iraq Codex Dataset
// Structured chronological data: 1920–2026
// Ready for timeline component in the STI module
// ═══════════════════════════════════════════════════════════════════

export interface CodexEvent {
  id: string;
  year: number;
  month?: number;
  title: string;
  titleAr?: string;
  category: "political" | "military" | "sectarian" | "economic" | "humanitarian" | "external";
  severity: "low" | "medium" | "high" | "critical";
  location?: string;
  actors?: string[];
  description: string;
  stiRelevance?: boolean;
  tags: string[];
}

export const iraqCodex: CodexEvent[] = [
  // ── 1920s: British Mandate ──────────────────────────────────────
  { id: "cx1920a", year: 1920, title: "Great Iraqi Revolution (Thawrat al-Ishrin)", titleAr: "ثورة العشرين", category: "military", severity: "critical", location: "Iraq", actors: ["Tribal confederations", "Shia clergy", "Sunni nationalism"], description: "Nationwide uprising against British occupation, spanning Shia shrine cities and Euphrates tribes. ~6,000 Iraqis killed. Led directly to creation of the Iraqi state in 1921.", stiRelevance: true, tags: ["mandate", "anti-british", "tribal", "shia", "1920"] },
  { id: "cx1921a", year: 1921, title: "Kingdom of Iraq established — Faisal I crowned", category: "political", severity: "medium", location: "Baghdad", actors: ["Faisal I", "British Empire"], description: "Hashemite Kingdom of Iraq established under British mandate. Faisal I brought from Hejaz. Sunni-dominated government despite Shia majority population.", stiRelevance: true, tags: ["monarchy", "hashemite", "british", "statehood"] },
  { id: "cx1932a", year: 1932, title: "Iraq granted independence — League of Nations admission", category: "political", severity: "medium", description: "Iraq becomes first Arab state admitted to League of Nations. British military advisors remain; air bases retained.", tags: ["independence", "league-of-nations", "british"] },
  { id: "cx1933a", year: 1933, title: "Simele massacre of Assyrians", category: "sectarian", severity: "critical", location: "Simele, Dohuk", actors: ["Iraqi Army", "Kurdish tribal militias"], description: "Army and irregular forces massacre 3,000–6,000 Assyrian Christians in northern Iraq following border incident. First mass atrocity of the Iraqi state.", stiRelevance: true, tags: ["assyrian", "massacre", "minorities", "dohuk"] },
  { id: "cx1936a", year: 1936, title: "First military coup — Bakr Sidqi", category: "political", severity: "high", actors: ["General Bakr Sidqi", "Hikmat Sulayman"], description: "First military coup in modern Arab history. Sidqi, a Kurd, deposes elected premier. Sets template for military politics in Iraq.", tags: ["coup", "military", "kurds"] },
  // ── 1940s–50s ──────────────────────────────────────────────────
  { id: "cx1941a", year: 1941, title: "Rashid Ali al-Gaylani coup — Anglo-Iraqi War", category: "military", severity: "critical", actors: ["Rashid Ali al-Gaylani", "Golden Square officers", "British Empire"], description: "Pro-Axis coup. British military intervention restores Hashemite rule. Iraq occupied for remainder of WWII.", tags: ["coup", "wwii", "pan-arab", "british"] },
  { id: "cx1941b", year: 1941, month: 6, title: "Farhud — Baghdad pogrom against Jews", titleAr: "الفرهود", category: "sectarian", severity: "critical", location: "Baghdad", description: "Two-day pogrom kills 180–600 Baghdad Jews, injures thousands, destroying 1,500 homes. Accelerates Jewish emigration from Iraq.", stiRelevance: true, tags: ["farhud", "jews", "pogrom", "baghdad", "1941"] },
  { id: "cx1948a", year: 1948, title: "al-Wathbah — Baghdad uprising", titleAr: "الوثبة", category: "political", severity: "high", location: "Baghdad", description: "Mass uprising against Portsmouth Treaty and British influence. Dozens killed. Government survives.", tags: ["wathba", "anti-british", "1948"] },
  { id: "cx1952a", year: 1952, title: "November Uprising — al-Nuwwab riots", category: "political", severity: "high", location: "Baghdad", description: "Riots against elections and government corruption. Martial law declared.", tags: ["riots", "uprising", "1952"] },
  { id: "cx1958a", year: 1958, month: 7, title: "14 July Revolution — End of Hashemite monarchy", titleAr: "ثورة 14 تموز", category: "political", severity: "critical", actors: ["Free Officers", "General Abdul Karim Qasim", "Colonel Abd al-Salam Arif"], description: "Military coup kills King Faisal II, Crown Prince Abd al-Ilah, and PM Nuri al-Said. Republic declared. Ends British influence. Qasim vs Arif conflict begins.", tags: ["revolution", "republic", "hashemite", "qasim", "1958"] },
  // ── 1960s ───────────────────────────────────────────────────────
  { id: "cx1961a", year: 1961, title: "Kurdish insurgency begins — Barzani revolt", category: "military", severity: "critical", location: "Kurdistan", actors: ["Mustafa Barzani", "KDP", "Iraqi Army"], description: "Mustafa Barzani launches armed uprising for Kurdish autonomy. First of four major Kurdish wars against Baghdad. War continues until 1970.", stiRelevance: true, tags: ["kurds", "barzani", "kdp", "insurgency", "1961"] },
  { id: "cx1963a", year: 1963, month: 2, title: "Ba'ath Party first coup — Qasim killed", category: "political", severity: "critical", actors: ["Ba'ath Party", "Arab Nationalist Movement"], description: "Ba'athists seize power with CIA knowledge. Qasim executed. Communist Party crushed. Ba'ath loses power again in November.", tags: ["baath", "cia", "coup", "1963"] },
  { id: "cx1968a", year: 1968, month: 7, title: "Ba'ath Party second coup — permanent rule begins", category: "political", severity: "critical", actors: ["Ba'ath Party", "Ahmed Hassan al-Bakr", "Saddam Hussein"], description: "Ba'ath Party seizes power in bloodless coup. Ahmed Hassan al-Bakr president, Saddam Hussein de facto security chief. Begins 35-year Ba'athist rule.", tags: ["baath", "saddam", "coup", "1968"] },
  { id: "cx1970a", year: 1970, title: "Kurdish autonomy agreement — March Manifesto", category: "political", severity: "medium", actors: ["Saddam Hussein", "Mustafa Barzani"], description: "Saddam Hussein negotiates autonomy with Kurds. Agreement collapses by 1974 over Kirkuk dispute.", tags: ["kurds", "autonomy", "barzani", "kirkuk"] },
  // ── 1970s ───────────────────────────────────────────────────────
  { id: "cx1972a", year: 1972, title: "Iraq Petroleum Company nationalized", category: "economic", severity: "high", location: "Iraq", description: "Iraq nationalizes IPC, ending British-American oil concession. Major economic turning point. Oil revenues fund state expansion.", tags: ["oil", "nationalization", "economic", "1972"] },
  { id: "cx1974a", year: 1974, title: "Second Kurdish war — Iranian-backed revolt", category: "military", severity: "critical", location: "Kurdistan", actors: ["Barzani", "KDP", "Iran", "CIA", "Iraq"], description: "Renewed Kurdish uprising backed by Iran and CIA. 50,000 peshmerga. Collapses after Algiers Agreement.", tags: ["kurds", "war", "iran", "cia", "peshmerga"] },
  { id: "cx1975a", year: 1975, title: "Algiers Agreement — Iran-Iraq border settlement", category: "political", severity: "high", actors: ["Saddam Hussein", "Shah of Iran"], description: "Iraq cedes Shatt al-Arab to Iran; Iran cuts support to Kurds. Kurdish movement collapses. Barzani dies in exile 1979.", tags: ["algiers", "iran", "kurds", "shatt-al-arab"] },
  { id: "cx1979a", year: 1979, month: 7, title: "Saddam Hussein assumes presidency — Ba'ath purge", category: "political", severity: "critical", actors: ["Saddam Hussein"], description: "Saddam forces al-Bakr to resign. Televised purge executes 22 senior Ba'ath officials. Absolute personal dictatorship established.", tags: ["saddam", "purge", "dictatorship", "1979"] },
  { id: "cx1979b", year: 1979, title: "Iranian Islamic Revolution — regional shockwave", category: "external", severity: "critical", actors: ["Ayatollah Khomeini", "Iran"], description: "Islamic Revolution in Iran. Shia clergy government alarms Saddam. DAWA party calls for similar revolution in Iraq. Mass executions of Shia activists begin.", stiRelevance: true, tags: ["iran", "revolution", "dawa", "shia", "khomeini"] },
  // ── 1980s ───────────────────────────────────────────────────────
  { id: "cx1980a", year: 1980, month: 9, title: "Iran-Iraq War begins", titleAr: "الحرب العراقية الإيرانية", category: "military", severity: "critical", actors: ["Iraq", "Iran"], description: "Iraq invades Iran. 8-year war kills 500,000–1 million. Uses chemical weapons. Ends in stalemate. Devastating economic and social cost.", stiRelevance: true, tags: ["iran-iraq-war", "saddam", "1980", "chemical-weapons"] },
  { id: "cx1982a", year: 1982, title: "SCIRI founded in Tehran — Badr Corps established", category: "political", severity: "high", actors: ["Iran", "SCIRI", "Badr Corps"], description: "Supreme Council for Islamic Revolution in Iraq founded by Shia exiles in Tehran. Badr Corps military wing formed. Forerunner of PMF Badr Organization.", stiRelevance: true, tags: ["sciri", "badr", "iran", "shia", "proxy"] },
  { id: "cx1986a", year: 1986, title: "Anfal Campaign begins — Kurdish genocide", titleAr: "حملة الأنفال", category: "sectarian", severity: "critical", location: "Kurdistan", actors: ["Ali Hassan al-Majid", "Iraqi Army"], description: "Saddam's Anfal campaign systematically destroys Kurdish villages. 50,000–182,000 Kurds killed. Chemical weapons used at Halabja (1988).", stiRelevance: true, tags: ["anfal", "genocide", "kurds", "chemical-weapons", "ali-chemical"] },
  { id: "cx1988a", year: 1988, month: 3, title: "Halabja chemical attack", titleAr: "مجزرة حلبجة", category: "sectarian", severity: "critical", location: "Halabja, Kurdistan", actors: ["Iraqi Army", "Ali Hassan al-Majid"], description: "Chemical weapon attack kills 3,000–5,000 Kurdish civilians in Halabja. Largest chemical weapons attack against civilians in history.", stiRelevance: true, tags: ["halabja", "chemical-weapons", "kurds", "genocide", "1988"] },
  // ── 1990s ───────────────────────────────────────────────────────
  { id: "cx1990a", year: 1990, month: 8, title: "Iraq invades Kuwait", category: "military", severity: "critical", location: "Kuwait", actors: ["Iraq", "Saddam Hussein"], description: "Iraq annexes Kuwait. UN sanctions imposed. Coalition of 35 nations assembled.", tags: ["kuwait", "invasion", "1990", "gulf-war"] },
  { id: "cx1991a", year: 1991, month: 1, title: "Gulf War — Operation Desert Storm", category: "military", severity: "critical", actors: ["US-led coalition", "Iraq"], description: "100-hour ground war. Iraq expelled from Kuwait. Saddam survives. Uprisings in south and north crushed with mass killings.", tags: ["gulf-war", "coalition", "desert-storm", "1991"] },
  { id: "cx1991b", year: 1991, month: 3, title: "Shia and Kurdish uprisings crushed", titleAr: "انتفاضة 1991", category: "sectarian", severity: "critical", location: "South Iraq, Kurdistan", actors: ["Republican Guard", "Shia rebels", "Kurdish peshmerga"], description: "Post-Gulf War uprisings in 14 of 18 governorates. Saddam's Republican Guard massacres tens of thousands of Shia. Kurds flee to Turkey. Mass graves discovered post-2003.", stiRelevance: true, tags: ["intifada", "shia", "kurds", "massacre", "1991"] },
  { id: "cx1991c", year: 1991, title: "No-fly zones established — Kurdish safe haven", category: "military", severity: "medium", actors: ["US", "UK", "France"], description: "No-fly zones north of 36°N and south of 33°N. Kurdish region achieves de facto autonomy.", tags: ["no-fly-zone", "kurds", "usa", "autonomy"] },
  { id: "cx1994a", year: 1994, title: "KDP-PUK civil war in Kurdistan", category: "military", severity: "critical", location: "Kurdistan", actors: ["KDP (Barzani)", "PUK (Talabani)"], description: "Intra-Kurdish civil war. KDP controls Erbil, PUK controls Sulaymaniyah. Thousands killed. Iran and Iraq both intervene. Ends with Washington Agreement 1998.", stiRelevance: true, tags: ["kdp", "puk", "kurdish-civil-war", "barzani", "talabani"] },
  // ── 2000s ───────────────────────────────────────────────────────
  { id: "cx2003a", year: 2003, month: 3, title: "US invasion of Iraq — Saddam regime falls", category: "military", severity: "critical", actors: ["US", "UK", "Coalition of the Willing", "Iraq"], description: "Coalition invasion topples Saddam Hussein in 21 days. Baghdad falls April 9. CPA established. De-Ba'athification and military disbandment begin.", stiRelevance: true, tags: ["invasion", "us", "2003", "saddam", "regime-change"] },
  { id: "cx2003b", year: 2003, month: 5, title: "CPA Order 1 & 2 — De-Ba'athification and army dissolution", category: "political", severity: "critical", actors: ["Paul Bremer", "CPA"], description: "CPA dissolves Ba'ath Party (removing 120,000 officials) and Iraqi Army (400,000 soldiers). Creates structural vacuum that fuels Sunni insurgency.", stiRelevance: true, tags: ["cpa", "de-baathification", "bremer", "insurgency", "2003"] },
  { id: "cx2004a", year: 2004, title: "Sunni insurgency and Fallujah battles", category: "military", severity: "critical", location: "Fallujah, Anbar", actors: ["Sunni insurgency", "AQI", "US Marines"], description: "First and Second Battles of Fallujah. AQI emerges. Abu Musab al-Zarqawi's network operational.", tags: ["fallujah", "sunni", "aqi", "zarqawi", "2004"] },
  { id: "cx2005a", year: 2005, title: "Iraq constitution and elections — sectarian political system", category: "political", severity: "high", description: "Three elections in 2005. New constitution establishes federal system. Sectarian identity politics institutionalized. Sunni boycott of January election.", stiRelevance: true, tags: ["constitution", "elections", "sectarianism", "2005"] },
  { id: "cx2006a", year: 2006, month: 2, title: "Samarra shrine bombing — sectarian civil war", titleAr: "تفجير مرقد العسكريين", category: "sectarian", severity: "critical", location: "Samarra", actors: ["AQI", "Shia militias", "Sunni insurgency"], description: "Al-Qaeda bombs the Al-Askari shrine (one of Shia Islam's holiest sites). Triggers full-scale Sunni-Shia civil war. 3,000 killed/month at peak.", stiRelevance: true, tags: ["samarra", "shrine", "civil-war", "aqia", "sectarian", "2006"] },
  { id: "cx2006b", year: 2006, month: 12, title: "Saddam Hussein executed", category: "political", severity: "medium", actors: ["Iraqi government"], description: "Saddam Hussein hanged for Dujail massacre. Execution video released on sectarian holiday, exacerbating tensions.", tags: ["saddam", "execution", "2006"] },
  { id: "cx2007a", year: 2007, title: "US troop surge — sectarian war suppressed", category: "military", severity: "high", actors: ["US Military", "General Petraeus", "Sunni Sahwa Councils"], description: "US surge of 30,000 troops plus Sunni Awakening movement ('Sahwa') suppress AQI. Violence drops 90% by 2008.", tags: ["surge", "petraeus", "sahwa", "awakening", "2007"] },
  { id: "cx2008a", year: 2008, title: "Basra Operation — Maliki asserts authority over Sadrists", category: "military", severity: "high", location: "Basra", actors: ["Maliki", "Iraqi Army", "Mahdi Army"], description: "PM Maliki launches 'Charge of the Knights' against Sadrist militia in Basra. Demonstrates growing state military capacity.", tags: ["basra", "maliki", "sadrists", "mahdi-army", "2008"] },
  { id: "cx2010a", year: 2010, title: "March elections — Maliki second term disputed", category: "political", severity: "high", actors: ["Nouri al-Maliki", "Ayad Allawi", "Iraqiyya"], description: "Iraqiyya wins most seats but Maliki forms government after 8-month crisis. Exclusion of Sunni political representation accelerates communal alienation.", stiRelevance: true, tags: ["elections", "maliki", "allawi", "sunni", "2010"] },
  { id: "cx2011a", year: 2011, month: 12, title: "US military withdrawal from Iraq", category: "military", severity: "high", actors: ["US Military"], description: "Last US troops withdraw. Iraq's security forces left facing AQI's successor networks. Political crisis deepens under Maliki.", tags: ["us-withdrawal", "maliki", "2011"] },
  // ── 2013–2017: ISIS rise and fall ──────────────────────────────
  { id: "cx2013a", year: 2013, title: "Hawija massacre — Sunni protest crackdown", category: "sectarian", severity: "critical", location: "Hawija, Kirkuk", actors: ["Iraqi Army", "Sunni protesters"], description: "Security forces kill 50+ Sunni protesters at Hawija sit-in camp. Radicalizes Sunni community. Accelerates ISIS recruitment.", stiRelevance: true, tags: ["hawija", "sunni", "protest", "maliki", "2013"] },
  { id: "cx2014a", year: 2014, month: 6, title: "ISIS seizes Mosul — Iraqi Army collapses", titleAr: "سقوط الموصل", category: "military", severity: "critical", location: "Mosul, Nineveh", actors: ["ISIS", "Iraqi Army"], description: "ISIS captures Iraq's second city in 3 days. 4 divisions (30,000 soldiers) flee. ISIS controls 1/3 of Iraq including Fallujah, Tikrit, Raqqa. Global shock.", stiRelevance: true, tags: ["isis", "mosul", "collapse", "2014"] },
  { id: "cx2014b", year: 2014, month: 6, title: "Grand Ayatollah Sistani issues fatwa — Popular Mobilization Forces founded", titleAr: "الحشد الشعبي", category: "political", severity: "critical", actors: ["Sistani", "PMF", "Iran"], description: "Sistani's jihad fatwa mobilizes 100,000+ volunteers. PMF (Hashed al-Sha'bi) formed, incorporating Iran-backed militias. Foundational moment for PMF as permanent force.", stiRelevance: true, tags: ["pmf", "hashed", "sistani", "fatwa", "iran", "2014"] },
  { id: "cx2014c", year: 2014, month: 8, title: "Yazidi genocide — Sinjar massacre", titleAr: "مجزرة شنجار", category: "sectarian", severity: "critical", location: "Sinjar, Nineveh", actors: ["ISIS", "Yazidis"], description: "ISIS enslaves thousands of Yazidi women, massacres men at Kocho. 5,000+ killed, 6,000+ enslaved. UN declares genocide. 400,000 displaced.", stiRelevance: true, tags: ["yazidi", "genocide", "sinjar", "isis", "2014"] },
  { id: "cx2015a", year: 2015, title: "Tikrit and Ramadi battles — PMF-Army offensive", category: "military", severity: "high", location: "Tikrit, Anbar", actors: ["PMF", "Iraqi Army", "Iran", "US Coalition"], description: "PMF-led recapture of Tikrit raises concerns about sectarian atrocities. Ramadi falls to ISIS then retaken. US coalition airstrikes begin.", tags: ["tikrit", "ramadi", "pmf", "coalition", "2015"] },
  { id: "cx2016a", year: 2016, title: "Mosul offensive begins", category: "military", severity: "high", location: "Mosul", actors: ["Iraqi Army", "PMF", "Peshmerga", "US Coalition"], description: "Coalition of 100,000 attacks Mosul. Nine-month battle. Most intense urban warfare since WWII. 10,000 civilians killed, 900,000 displaced.", tags: ["mosul", "offensive", "liberation", "2016"] },
  { id: "cx2017a", year: 2017, month: 7, title: "Mosul liberated from ISIS", category: "military", severity: "high", location: "Mosul", actors: ["Iraqi Army", "US Coalition"], description: "Mosul Old City liberated after bitter battle. ISIS Caliphate in Iraq effectively ended. But underground insurgency continues.", tags: ["mosul", "liberation", "isis", "2017"] },
  { id: "cx2017b", year: 2017, month: 9, title: "Kurdistan independence referendum", category: "political", severity: "critical", location: "Kurdistan Region", actors: ["KDP", "PUK", "Turkish government", "Iranian government", "Iraqi government"], description: "93% vote for independence. Baghdad, Ankara, Tehran, Washington oppose. Leads to military confrontation at Kirkuk.", stiRelevance: true, tags: ["referendum", "independence", "kdp", "puk", "2017"] },
  { id: "cx2017c", year: 2017, month: 10, title: "Kirkuk recaptured by PMF-Army — Kurdish defeat", category: "military", severity: "critical", location: "Kirkuk", actors: ["PMF", "Iraqi Army", "KDP", "PUK"], description: "PMF and Iraqi Army seize Kirkuk from Kurdish forces in 3 hours. PUK stands down. KDP loses oil revenue. Kurdish political crisis deepens.", stiRelevance: true, tags: ["kirkuk", "pmf", "kdp", "puk", "oil", "2017"] },
  // ── 2019–2026: Post-ISIS era ────────────────────────────────────
  { id: "cx2019a", year: 2019, month: 10, title: "October Revolution — mass protests", titleAr: "ثورة أكتوبر", category: "political", severity: "critical", location: "Baghdad, South Iraq", actors: ["Iraqi youth", "Tishreen movement", "PMF militias"], description: "Largest protests in modern Iraqi history. 600+ killed, mostly by PMF snipers. Demands end to Iranian influence and sectarian political system.", stiRelevance: true, tags: ["tishreen", "october-revolution", "protests", "pmf", "iran", "2019"] },
  { id: "cx2020a", year: 2020, month: 1, title: "US kills Qasem Soleimani and Abu Mahdi al-Muhandis at Baghdad Airport", category: "external", severity: "critical", location: "Baghdad International Airport", actors: ["US", "Qasem Soleimani", "Abu Mahdi al-Muhandis", "IRGC"], description: "US drone strike kills Iran's top general and PMF commander simultaneously. Iraq demands US withdrawal. Threatens regional war. PMF rockets intensify against US forces.", stiRelevance: true, tags: ["soleimani", "muhandis", "us", "iran", "pmf", "2020"] },
  { id: "cx2021a", year: 2021, title: "Kazemi government — reform attempt", category: "political", severity: "medium", actors: ["Mustafa al-Kazemi"], description: "Former intelligence chief attempts balanced governance. Limited success against Iran-aligned militias. Survives assassination attempt (drone attack on residence).", tags: ["kazemi", "reform", "pmf", "2021"] },
  { id: "cx2021b", year: 2021, month: 10, title: "Iraqi elections — Sadrist bloc wins, Iran-aligned bloc collapses", category: "political", severity: "high", actors: ["Muqtada al-Sadr", "PMF parties", "Kataib Hezbollah"], description: "Sadr wins 73 seats. Iran-aligned Coordination Framework loses seats. Disputed results. Months of political paralysis.", stiRelevance: true, tags: ["elections", "sadr", "pmf", "coordination-framework", "2021"] },
  { id: "cx2022a", year: 2022, month: 8, title: "Green Zone stormed by Sadrists — near civil war", category: "political", severity: "critical", location: "Baghdad", actors: ["Sadrists", "Coordination Framework militias", "Iraqi Army"], description: "Sadrists storm Green Zone and Parliament. Militia-on-militia fighting kills 30+. Sadr announces retirement. Crisis ends after 4 days.", stiRelevance: true, tags: ["sadr", "green-zone", "militia", "political-crisis", "2022"] },
  { id: "cx2022b", year: 2022, month: 10, title: "Mohammed Shia' al-Sudani elected PM", category: "political", severity: "medium", actors: ["Sudani", "Coordination Framework"], description: "Iran-aligned Coordination Framework backs Sudani as compromise PM after year of deadlock. Sadr accepts outcome without formal participation.", tags: ["sudani", "pm", "coordination-framework", "2022"] },
  { id: "cx2023a", year: 2023, title: "Kirkuk-Ceyhan pipeline suspended — KRI oil revenue dispute", category: "economic", severity: "high", location: "Kirkuk, Turkey", actors: ["KRG", "Baghdad", "Turkey"], description: "International arbitration halts 450,000 bpd Kirkuk-Ceyhan pipeline. KRG loses $1B/month. Baghdad-KRG revenue dispute intensifies.", stiRelevance: true, tags: ["kirkuk", "oil", "pipeline", "krg", "turkey", "2023"] },
  { id: "cx2024a", year: 2024, title: "PMF formally integrated into Iraqi armed forces", category: "political", severity: "high", actors: ["Sudani", "PMF", "Iran"], description: "Sudani government advances PMF institutional integration. Iran-aligned factions consolidate military-political power. Reform movement constrained.", stiRelevance: true, tags: ["pmf", "integration", "army", "iran", "sudani", "2024"] },
  { id: "cx2025a", year: 2025, title: "Sinjar status negotiations collapse — Yazidi return stalled", category: "humanitarian", severity: "high", location: "Sinjar, Nineveh", actors: ["KRG", "Baghdad", "Yazidi community", "PKK-linked factions"], description: "UN-brokered Sinjar Agreement remains unimplemented. 200,000 Yazidis unable to return. PKK-linked NPÊ militia refuses to disarm. Baghdad-KRG deadlock.", stiRelevance: true, tags: ["sinjar", "yazidi", "pkk", "displacement", "krg", "2025"] },
  { id: "cx2026a", year: 2026, title: "Current: STI composite at 65 (HIGH) — Arab-Kurd-Turkmen axis elevated", category: "political", severity: "high", location: "Iraq", description: "Ongoing multi-vector tension: KDP-PUK revenue dispute, PMF-Sunni confrontation in disputed territories, Yazidi non-return, Kurdish oil market contraction. Current MERIDIAN monitoring period.", stiRelevance: true, tags: ["current", "sti", "kurds", "sunni", "pmf", "2026"] },
];

// ── Helper functions ──────────────────────────────────────────────

export function getEventsByYear(year: number): CodexEvent[] {
  return iraqCodex.filter(e => e.year === year);
}

export function getEventsByCategory(cat: CodexEvent["category"]): CodexEvent[] {
  return iraqCodex.filter(e => e.category === cat);
}

export function getEventsByDecade(decade: number): CodexEvent[] {
  return iraqCodex.filter(e => Math.floor(e.year / 10) * 10 === decade);
}

export function getStiRelevantEvents(): CodexEvent[] {
  return iraqCodex.filter(e => e.stiRelevance);
}

export const codexYearRange = {
  min: Math.min(...iraqCodex.map(e => e.year)),
  max: Math.max(...iraqCodex.map(e => e.year)),
};
