export {
  Cpu,
  HardDrives as Server,
  Terminal as TerminalSquare,
  PlayCircle,
  Rss,
  Eye as ScanEye,
  PaperPlaneRight as Send,
  CaretRight as ChevronRight,
  Stack as Layers,
  Minus,
  CheckCircle,
  Database,
  ChartBar as CandlestickChart,
  Graph as Workflow,
  Crosshair,
  ArrowRight,
  Broadcast as RadioTower,
  Info,
  MagnifyingGlass as Search,
  X,
  Play,
  Plus,
  Lightning as Zap,
  SpeakerHifi as Radio,
  Anchor,
  Waves,
  Eye,
  MapPin,
  Clock,
  Funnel as Filter,
  Crosshair as Locate,
  CircleNotch as Loader2,
  CornersOut as Maximize,
  Crosshair as Radar,
  Faders as Settings2,
  Camera,
  ShieldWarning as ShieldAlert,
  Graph as Network,
  Target,
  Fire as Flame,
  Shield,
  Planet as Orbit,
  Warning as AlertTriangle,
  Phone,
  Fingerprint,
  FileText,
  TrendUp as TrendingUp,
  ArrowsClockwise as RefreshCw,
  Bell,
  Lock,
  TrendDown as TrendingDown,
  BellRinging as BellRing,
  ArrowSquareOut as ExternalLink,
  ChartBar as BarChart3,
  Newspaper,
  Sparkle as Sparkles,
  Command,
  Planet as Satellite,
  Brain,
  GlobeHemisphereWest as Globe,
  Pause,
  Pulse as Activity,
  Users,
  GlobeHemisphereWest as Globe2,

  // ── Terrain-specific domain icons ──────────────────────
  AirplaneTilt,
  SecurityCamera,
  Boat,
  Fire,
  Siren,
  GasPump,
  MapTrifold,
  WaveSine,
  Broadcast,
  Binoculars,
  Thermometer,
  RocketLaunch,
  ShieldCheck,
  NavigationArrow,
  Copy,
} from "@phosphor-icons/react";
